# Generated by Django 2.2.9 on 2020-07-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to=''),
        ),
    ]
