# Generated by Django 2.2.9 on 2020-07-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200730_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='account',
        ),
    ]
