# Generated by Django 2.2.9 on 2020-07-29 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200730_0723'),
        ('products', '0008_auto_20200730_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
