# Generated by Django 2.2.9 on 2020-07-29 16:03

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_number', phone_field.models.PhoneField(max_length=31)),
                ('address', models.CharField(max_length=140)),
            ],
        ),
    ]
